### ISSUE TITLE
Display with image instead of unicode

### ISSUE THREAD

**Issue by jcs090218** [dunn/company-emoji#17]
I have trouble displaying unicode, similar to #3.

Would it be nice to display with image instead of the character? The following code might help with this feature! Thanks!

https://github.com/company-mode/company-mode/blob/d77184094b9a45b204813d824918e1ec2aac8504/company.el#L1552-L1589

**Comment by dunn** [comment]
i'd be open to a PR that made that an option, but it's probably not something i'll do myself
