### ISSUE TITLE
Use newer gemoji

### ISSUE THREAD

**Issue by sdhoward** [dunn/company-emoji#18]
I just noticed that in my completion list I'm missing a few of my new favorites. This happened before and was fixed with 79ed90c6eb278605d19245426f59296e0fa4010d. Would it be possible to generate a new version using gemoji 4.1.0?

https://github.com/github/gemoji/releases

**Comment by dunn** [comment]
https://github.com/dunn/company-emoji/commit/b4454976ded8c46a4db59283f0907400ec52a776
