### ISSUE TITLE
submit to MELPA & Cocoa support.

### ISSUE THREAD

**Issue by waymondo** [dunn/company-emoji#2]
This package is great! I would encourage you to submit this to [MELPA](http://melpa.org/) for easy installs through `package.el`.

Regarding your note about having issues with Cocoa support - you can register Apple's emoji unicode font with the following snippet (for 10.10 at least):

```
(when (eq system-type 'darwin)
  (set-fontset-font t 'symbol (font-spec :family "Apple Color Emoji") nil 'prepend))
```

Then everything works as expected. For reference, this is how I build Emacs with Homebrew:

```
brew install emacs --with-cocoa --HEAD
```

**Comment by dunn** [comment]
:ok_woman: https://github.com/milkypostman/melpa/pull/2995

Thanks for the Cocoa help!  It had to be complicated a bit to work with `emacsclient` but otherwise it's perfect!

**Comment by dunn** [comment]
The recipe was accepted ✔️

**Comment by waymondo** [comment]
:saxophone:
