### ISSUE TITLE
Emojis not displayed correctly

### ISSUE THREAD

**Issue by flyck** [dunn/company-emoji#3]
Are there any prerequesites to this pacakge?
I can display jpegs (see screenshot)
![company-emoji on windows](https://cloud.githubusercontent.com/assets/11775168/9311051/24656602-4514-11e5-8b37-c682be00481b.png)

**Comment by dunn** [comment]
Unfortunately I don't have a Windows setup to test on, but it looks like you don't have full Unicode support.  Do you have something like `(set-language-environment "UTF-8")` in your init file? (There are [a few other settings you can try](http://stackoverflow.com/a/17537564) if that doesn't help.)

**Comment by felipebueno** [comment]
Hi, @dunn 

I'm on linux and having the same encoding problem. :(

![screenshot from 2015-08-18 10 31 41](https://cloud.githubusercontent.com/assets/241271/9331234/a338707a-4594-11e5-908a-66c080ebacea.png)

**Comment by dunn** [comment]
Well, dang.  I can test on Linux, though, so I'll do that as soon as I can.

**Comment by dunn** [comment]
I'm having, uh, issues with my Linux machine right now so I can't test it but looks like @syohex has the answer here: https://github.com/syohex/emacs-ac-emoji#linux-users

Basically most Linux distros don't come with fonts that support emoji, so you need to install one.

I'm not sure if it's the same issue with Windows; I thought modern versions of Windows supported emoji by default. What version do you have, @BubblesToTheLimit?

**Comment by BubblesToTheLimit** [comment]
I appreciate you looking further into this issue. I'm running Windows 10.
I tried the suggested solution on my xubuntu-vm but it doesn't seem to find the Symbola-font I installed previously. To solve this issue I guess I have to dive deeper into fonts on Linux, currently I am a complete beginner at this.

As this seems to be a font-installation problem on Linux on the users-side feel free to close this issue ^.^
Best Regards, Bubbles

**Comment by BubblesToTheLimit** [comment]
I appreciate you looking further into this issue. I'm running Windows 10.
I tried the suggested solution on my xubuntu-vm but it doesn't seem to find the Symbola-font I installed previously. To solve this issue I guess I have to dive deeper into fonts on Linux, currently I am a complete beginner at this.

As this seems to be a font-installation problem on Linux on the users-side I'll close this issue ^.^
Maybe you could leave a hint that display-problems are related to a missing font in the Readme.md?
Best Regards, Bubbles

**Comment by flyck** [comment]
I appreciate you looking further into this issue. I'm running Windows 10.
 I tried the suggested solution on my xubuntu-vm but it doesn't seem to find the Symbola-font I installed previously. To solve this issue I guess I have to dive deeper into fonts on Linux, currently I am a complete beginner at this.

As this seems to be a font-installation problem on Linux on the users-side I'll close this issue ^.^
 Maybe you could leave a hint that display-problems are related to a missing font in the Readme.md?
 Best Regards, Bubbles

**Comment by dunn** [comment]
You should be able to just toss Symbola.ttf into `/usr/share/fonts/truetype`, but on Debian I had to install Symbola through apt: `apt-get install ttf-ancient-fonts`.  I'll add another note to the readme.

**Comment by manuel-uberti** [comment]
Hi, sorry to post in a closed issue (if you need me to open a new one, please ask).
I am on Debian, I have Symbola installed and setup on Emacs like this:

```
(set-fontset-font t script (font-spec :family "Symbola")
                      frame 'prepend)
```

Some of the emojis are not displayed correctly, as you can see in the following image
![emoji](https://cloud.githubusercontent.com/assets/8199224/11191919/7084713c-8c9e-11e5-948a-6cadfb42a23b.png)

**Comment by dunn** [comment]
I'll see if I can reproduce this on my Debian machine when I get a chance, thanks!

**Comment by manuel-uberti** [comment]
Don't know if this can be helpful, but here more details:
- Debian unstable (kernel `Linux 4.3.0-towo.3-siduction-amd64 x86_64`)
- `GNU Emacs 25.0.50.1` (branch: `emacs-25`)

**Comment by dunn** [comment]
Sort of forgot about this, but: I did see the same thing, but before I could troubleshoot much further my Linux machine died.  So I'm not sure yet if this problem originates with company-emoji, or Emacs, or the Symbola font.
