### ISSUE TITLE
emacs-emojify integration

### ISSUE THREAD

**Issue by manuel-uberti** [dunn/company-emoji#5]
Hi,

thanks for this great package. This is a question, not an issue per se. I was wondering if company-emoji could work with [emacs-emojify](https://github.com/iqbalansari/emacs-emojify).

This would be useful for Linux users who want colored emojis.

**Comment by dunn** [comment]
emacs-emojify converts `:shortcodes:` on the fly to PNGs, is that right?

In that case what might work is setting the custom variable `company-emoji-insert-unicode` to `nil` so company-emoji doesn't replace the shortcodes with Unicode emoji.

**Comment by manuel-uberti** [comment]
Yes, it works! Thank you very much.
